name = "SearchableGeometries"
uuid = "0d49ff20-b62b-4542-99e1-46442543f9f8"
authors = ["Christina Taylor <cgtaylor@boisestate.edu>", "Emmanuel Kwame Ayanful <emmanuelayanful@u.boisestate.edu>"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
